### ISSUE TITLE
backend - memberships view -  Notice: Undefined property: stdClass::$end

### ISSUE THREAD

**Issue by JKoelman** [momo10216/clubmgnt#10]
error notice `Notice: Undefined property: stdClass::$end in C:\wamp\www\0211\administrator\components\com_clubmanagement\views\memberships\tmpl\default_body.php on line 39`

the memberships model, "protected function getListQuery()", is retrieving 2 times m.begin abd it would be good to replace of them with m.end.

**Comment by momo10216** [comment]
Should be fixed with the next version
