### ISSUE TITLE
backend - boardentries - Notice: Undefined property: stdClass::$birthday 

### ISSUE THREAD

**Issue by JKoelman** [momo10216/clubmgnt#11]
with board i was thinking about a bulletin board / forum but did find out it was something different in your component.

`Error Notice: Undefined property: stdClass::$birthday in ......\administrator\components\com_clubmanagement\views\boardentries\tmpl\default_body.php on line 30`

it happens as the function in the model is not retrieving all the needed fields

**Comment by momo10216** [comment]
Should be fixed with the next version
