### ISSUE TITLE
front - memberships view - Notice: Undefined index: name

### ISSUE THREAD

**Issue by JKoelman** [momo10216/clubmgnt#13]
`Notice: Undefined index: name in ......\components\com_clubmanagement\models\memberships.php on line 182`

it's pointing to this line `if ($allFields[$key])` and that's correct becasue if you do a var_dump to see what's in that $allFields variable you'll see why it's having an issue. The indexes or a bit of code is indeed not correct.

there is a second note `Notice: Undefined index: in ....\components\com_clubmanagement\models\memberships.php on line 202`

**Comment by momo10216** [comment]
Strange issue. The index "name" should never exist. It should be "person_name", but i cannot find the root of this cause (columns come from cmmembershipcolumn).

**Comment by momo10216** [comment]
Should not happen anymore with 3.2.5
