### ISSUE TITLE
Import functions

### ISSUE THREAD

**Issue by ptrouw** [momo10216/clubmgnt#15]
Hey,
Thx for nice component. Can you tell me what the format is for import?
Cheers Paul

**Comment by momo10216** [comment]
Enter some sample date and use export. The format is CSV (Character Separate Version). For separation the character Tab is used. The first line containes the name of the fields.

Use LibreOffice Calc / Microsoft Excel to format your date and export it as CSV.

Regards Norbert

**Comment by momo10216** [comment]
I need to dokument this in the wiki.

**Comment by uelib** [comment]
I tried it, but it ends in error.  :-(

**Comment by momo10216** [comment]
Added entry to [FAQ](https://github.com/momo10216/clubmgnt/wiki/FAQ).
