### ISSUE TITLE
Error: Board List as Business Cards with "show detail" on

### ISSUE THREAD

**Issue by uelib** [momo10216/clubmgnt#17]
I defined a menu for "Member of the board" (Vorstand) as business cards and defined property "Name" as link to detail of Person.
When opening menu am ErrorException occurs! "Call to a member function get() on null".

![image](https://cloud.githubusercontent.com/assets/16066623/18615793/37d45ef2-7db0-11e6-997a-ad116767b19c.png)

Environment & details:

GET Data empty
POST Data empty
Files empty
Cookies
a7294ed465347d29b019c8d4d7e83c24    kp24qhkpqur3nos3f4atm0jqk4
efb95ea442e55489870cc2c34b72dcbf    s9jc6vclannrbm2gad8r2lfpa2
Session
joomla  TzoyNDoiSm9vbWxhXFJlZ2lzdHJ5XFJlZ2lzdHJ5IjoyOntzOjc6IgAqAGRhdGEiO086ODoic3RkQ2xhc3MiOjE6e3M6OToiX19kZWZhdWx0IjtPOjg6InN0ZENsYXNzIjozOntzOjc6InNlc3Npb24iO086ODoic3RkQ2xhc3MiOjQ6e3M6NzoiY291bnRlciI7aTozOTtzOjU6InRpbWVyIjtPOjg6InN0ZENsYXNzIjozOntzOjU6InN0YXJ0IjtpOjE0NzQyMDExMTQ7czo0OiJsYXN0IjtpOjE0NzQyMDI5MTQ7czozOiJub3ciO2k6MTQ3NDIwMzI3Njt9czo2OiJjbGllbnQiO086ODoic3RkQ2xhc3MiOjE6e3M6OToiZm9yd2FyZGVkIjtzOjEyOiI1LjE0OS4zOC4yNTMiO31zOjU6InRva2VuIjtzOjMyOiJidDdKaVpLY2IxeVh3bFRYdDFtUTVUZDFEZkVReENTdSI7fXM6ODoicmVnaXN0cnkiO086MjQ6Ikpvb21sYVxSZWdpc3RyeVxSZWdpc3RyeSI6Mjp7czo3OiIAKgBkYXRhIjtPOjg6InN0ZENsYXNzIjowOnt9czo5OiJzZXBhcmF0b3IiO3M6MToiLiI7fXM6NDoidXNlciI7Tzo1OiJKVXNlciI6MTp7czoyOiJpZCI7aTowO319fXM6OToic2VwYXJhdG9yIjtzOjE6Ii4iO30=
Server/Request Data
PATH    /usr/local/bin:/usr/bin:/bin
PP_CUSTOM_PHP_INI   /srv/www/vhosts/system/test.sac-burgdorf.ch/etc/php.ini
PP_CUSTOM_PHP_CGI_INDEX plesk-php56-fastcgi
PATH_TRANSLATED /srv/www/vhosts/sac-burgdorf.ch/subdomains/test/httpdocs/vorstand
PATH_INFO   /vorstand
SCRIPT_NAME /index.php
REQUEST_URI /index.php/vorstand
QUERY_STRING  
REQUEST_METHOD  GET
SERVER_PROTOCOL HTTP/1.0
GATEWAY_INTERFACE   CGI/1.1
REMOTE_PORT 53428
SCRIPT_FILENAME /srv/www/vhosts/sac-burgdorf.ch/subdomains/test/httpdocs/index.php
SERVER_ADMIN    postmaster@pleskadmin.hostfactory.ch
DOCUMENT_ROOT   /srv/www/vhosts/sac-burgdorf.ch/subdomains/test/httpdocs
REMOTE_ADDR 5.149.38.253
SERVER_PORT 80
SERVER_ADDR 62.146.13.245
SERVER_NAME test.sac-burgdorf.ch
SERVER_SOFTWARE Apache
SERVER_SIGNATURE  
Apache Server at test.sac-burgdorf.ch Port 80
HTTP_COOKIE a7294ed465347d29b019c8d4d7e83c24=kp24qhkpqur3nos3f4atm0jqk4; efb95ea442e55489870cc2c34b72dcbf=s9jc6vclannrbm2gad8r2lfpa2
HTTP_ACCEPT_LANGUAGE    de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
HTTP_ACCEPT_ENCODING    gzip, deflate, sdch
HTTP_REFERER    http://test.sac-burgdorf.ch/index.php/benutzer
HTTP_ACCEPT text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8
HTTP_USER_AGENT Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36
HTTP_UPGRADE_INSECURE_REQUESTS  1
HTTP_CACHE_CONTROL  max-age=0
HTTP_CONNECTION close
HTTP_X_ACCEL_INTERNAL   /internal-nginx-static-location
HTTP_X_FORWARDED_FOR    5.149.38.253
HTTP_X_REAL_IP  5.149.38.253
HTTP_HOST   test.sac-burgdorf.ch
SCRIPT_URI  http://test.sac-burgdorf.ch/index.php/vorstand
SCRIPT_URL  /index.php/vorstand
UNIQUE_ID   V96OjD6SDfIAADrSe0cAAAAD
FCGI_ROLE   RESPONDER
PHP_SELF    /index.php/vorstand
REQUEST_TIME_FLOAT  1474203276.5254
REQUEST_TIME    1474203276
Environment Variables empty
Registered Handlers

**Comment by momo10216** [comment]
Fixed with version 3.0.15
