### ISSUE TITLE
Import and other problems

### ISSUE THREAD

**Issue by Ralf16** [momo10216/clubmgnt#19]
Thank you for the "Club Management"-module.
It could be the module, I´m looking for.

But some things dosn´t work :-(
For example the import of members. 
As a test I exported so members, delete them in the module und tried to import them again.
This ist the message, I´ve got:
1054 Unknown column 'Array' in 'field list' SQL=INSERT INTO `#__nokCM_memberships` (Array,`type`,`begin`,`end`,`published`,`createdby`,`createddate`,Array) VALUES ('Ammoneit','ACTIVE','2016-11-02','0000-00-00','1','\'740\'','0000-00-00 00:00:00','41')

**Comment by momo10216** [comment]
Tested, üplease try again with latest version.
Added entry to [FAQ](https://github.com/momo10216/clubmgnt/wiki/FAQ).
