### ISSUE TITLE
Image sizes and password protection

### ISSUE THREAD

**Issue by MartinvP** [momo10216/clubmgnt#20]
I like this simple and useful component.

There are two issues however:
1. Image sizes on the membership cards vary crazily. 
All originals are 240 x 320 pixels and set to show at 100%. Still it looks like this:
![clubmanagement](https://user-images.githubusercontent.com/29405225/27087475-70400fa2-5055-11e7-88b4-5a480b1c2022.png)
2. Is there a simple way to password protect the membership cards?

Best R's
/Martin

**Comment by momo10216** [comment]
Fixed with 3.0.14
