### ISSUE TITLE
Error when trying to import people

### ISSUE THREAD

**Issue by w8pif** [momo10216/clubmgnt#29]
I get an error when I click on the "Import" people button....

Warning: count(): Parameter must be an array or an object that implements Countable in  /administrator/components/com_clubmanagement/views/persons/view.html.php on line 34

Result after attempted import:  1054 Unknown column 'Array' in 'field list'

**Comment by momo10216** [comment]
Should be fixed with 3.0.22

**Comment by momo10216** [comment]
Should be fixed with 3.0.22
