### ISSUE TITLE
Backend - View Person - Notice: Undefined variable: directory

### ISSUE THREAD

**Issue by JKoelman** [momo10216/clubmgnt#4]
Hi there,

Have to say that i'm testing the component just to see what it does and how it should be working.
Maybe it's a component that i can use for the "neighborhood association" but have to see.
--> When i do see some error notices i'll report them. 

`Notice: Undefined variable: directory in .....\administrator\components\com_clubmanagement\models\fields\cmimagelist.php on line 39`

it happens as you did define a $dir but am calling it as $directory at that line.

**Comment by JKoelman** [comment]
> " but have to see.

have to say that i'm probably better off with creating something myself as there are some features i do like to add.

ah well, I do hope you will continue the work.

**Comment by momo10216** [comment]
Should be fixed with the next version.
