### ISSUE TITLE
Backend - view persons - Notice: Undefined property: stdClass::$state / $country

### ISSUE THREAD

**Issue by JKoelman** [momo10216/clubmgnt#5]
This error notice `Notice: Undefined property: stdClass::$state in .....\administrator\components\com_clubmanagement\views\persons\tmpl\default_body.php on line 36`

 Notice: Undefined property: stdClass::$country in .....\administrator\components\com_clubmanagement\views\persons\tmpl\default_body.php on line 39

The problem occurs as the "protected function getListQuery()" within the backend persons model is not retrieving the needed columns/fields.

**Comment by JKoelman** [comment]
the line can be changed to `->select($db->quoteName(array('p.id', 'p.name', 'p.firstname', 'p.address', 'p.zip', 'p.city','p.country','p.state')))`

**Comment by momo10216** [comment]
Should be fixed with the next version.
