### ISSUE TITLE
Backend - Membership view - Strict standards: Only variables should be assigned by reference

### ISSUE THREAD

**Issue by JKoelman** [momo10216/clubmgnt#7]
Strict standards: Only variables should be assigned by reference in ......\administrator\components\com_clubmanagement\models\fields\cmselection.php on line 24

the note is pointing to this line `$app = &JFactory::getApplication();` and that's correct as the & sign is there. when removed the notice will be gone.

**Comment by momo10216** [comment]
Should be fixed with the next version.
