### ISSUE TITLE
backend - view person - tmpl modal - Notice: Undefined property: stdClass::$birthday 

### ISSUE THREAD

**Issue by JKoelman** [momo10216/clubmgnt#9]
it happens as the query within the persons model is not retrieving all the needed fields.
so it would be good to update the query.

error notice `Notice: Undefined property: stdClass::$birthday in ....\administrator\components\com_clubmanagement\views\persons\tmpl\modal_body.php on line 31`

**Comment by momo10216** [comment]
Should be fixed with the next version
